GET http://localhost:3000
###
GET http://localhost:3000/users
###
GET http://localhost:3000/users/1
###
POST http://localhost:3000/users
 Content-Type: application/json

 {
    
    "full_name": "ann ",
    "email": "ann@gmail.com",
    "password": "123456",
    "role": "admin"
    

 }
###
PUT http://localhost:3000/users/8
 Content-Type: application/json

 {
        
    "email": "annie@gmail.Com"
 }

###
DELETE http://localhost:3000/users/8