GET http://localhost:3000
//users queries
###
GET http://localhost:3000/users
###
GET http://localhost:3000/users/1
###
POST http://localhost:3000/users
 Content-Type: application/json

 {
    
    "full_name": "ann ",
    "email": "ann@gmail.com",
    "password": "123456",
    "role": "admin"
    

 }
###
PUT http://localhost:3000/users/9
 Content-Type: application/json

 {
        
    "email": "annie@gmail.Com"
 }

###
DELETE http://localhost:3000/users/8

//vehicles queries

###
GET http://localhost:3000/vehicles
###
GET http://localhost:3000/vehicles/1
###
POST http://localhost:3000/vehicles
 Content-Type: application/json

  {
 "make":"toyota",
 "model":"premio",
 "year":"2012",
 "vin":"123455",
 "status":"available",
 "price":"2000000"
  }
###
PUT http://localhost:3000/vehicles/1
 Content-Type: application/json

 {
   "year":"2017"
 }

###
DELETE http://localhost:3000/vehicles/1

//vehiles Status queries
###
GET http://localhost:3000/vehicleStatus
###
GET http://localhost:3000/vehicleStatus/1
###
POST http://localhost:3000/vehicleStatus
 Content-Type: application/json

 {
   "vehicle_id":"6",
   "status":"available",
   "description":"available"
 }

###
PUT http://localhost:3000/vehicleStatus/3
 Content-Type: application/json

 {
   "status":"available"
 }
###
DELETE http://localhost:3000/vehicleStatus/9

//transactions queries
###
GET http://localhost:3000/transactions
###
GET http://localhost:3000/transactions/1
###
POST http://localhost:3000/transactions
 Content-Type: application/json

 {
  "vehicle_id":"6",
  "buyer_id":"1",
  "sale_price":"2000000",
  "status":"sold"
 }

###
PUT http://localhost:3000/transactions/1
 Content-Type: application/json

 {
  "status":"sold"
 }

###
DELETE http://localhost:3000/transactions/1